const inspirationalQuotes = [
  "The only way to do great work is to love what you do. — Steve Jobs",
  "Believe you can and you're halfway there. — Theodore Roosevelt",
  "It does not matter how slowly you go as long as you do not stop. — Confucius",
  "The future belongs to those who believe in the beauty of their dreams. — Eleanor Roosevelt",
  "Act as if what you do makes a difference. It does. — William James",
  "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us. — Ralph Waldo Emerson",
  "In the middle of every difficulty lies opportunity. — Albert Einstein",
  "You are never too old to set another goal or to dream a new dream. — C.S. Lewis",
  "The best time to plant a tree was 20 years ago. The second best time is now. — Chinese Proverb",
  "Your time is limited, don't waste it living someone else's life. — Steve Jobs",
  "If you want to lift yourself up, lift up someone else. — Booker T. Washington",
  "Everything you've ever wanted is on the other side of fear. — George Addair",
  "The only impossible journey is the one you never begin. — Tony Robbins",
  "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
  "Hardships often prepare ordinary people for an extraordinary destiny. — C.S. Lewis",
  "Do what you can, with what you have, where you are. — Theodore Roosevelt",
  "Happiness is not something ready-made. It comes from your own actions. — Dalai Lama",
  "The secret of getting ahead is getting started. — Mark Twain",
  "It always seems impossible until it's done. — Nelson Mandela",
  "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
  "You miss 100% of the shots you don't take. — Wayne Gretzky",
  "Whether you think you can or you think you can't, you're right. — Henry Ford",
  "The mind is everything. What you think you become. — Buddha",
  "Strive not to be a success, but rather to be of value. — Albert Einstein",
  "I have not failed. I've just found 10,000 ways that won't work. — Thomas Edison",
  "A person who never made a mistake never tried anything new. — Albert Einstein",
  "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
  "What you get by achieving your goals is not as important as what you become by achieving your goals. — Zig Ziglar",
  "Life is 10% what happens to us and 90% how we react to it. — Charles R. Swindoll",
  "Creativity is intelligence having fun. — Albert Einstein",
  "The way to get started is to quit talking and begin doing. — Walt Disney",
  "If you look at what you have in life, you'll always have more. — Oprah Winfrey",
  "Life is what happens when you're busy making other plans. — John Lennon",
  "Spread love everywhere you go. Let no one ever come to you without leaving happier. — Mother Teresa",
  "When you reach the end of your rope, tie a knot in it and hang on. — Franklin D. Roosevelt",
  "Don't judge each day by the harvest you reap but by the seeds that you plant. — Robert Louis Stevenson",
  "The best revenge is massive success. — Frank Sinatra",
  "People who are crazy enough to think they can change the world are the ones who do. — Rob Siltanen",
  "If you really look closely, most overnight successes took a long time. — Steve Jobs",
  "The purpose of our lives is to be happy. — Dalai Lama",
  "Turn your wounds into wisdom. — Oprah Winfrey",
  "We may encounter many defeats but we must not be defeated. — Maya Angelou",
  "Knowing is not enough; we must apply. Wishing is not enough; we must do. — Johann Wolfgang von Goethe",
  "Imagine your life is perfect in every respect; what would it look like? — Brian Tracy",
  "We generate fears while we sit. We overcome them by action. — Dr. Henry Link",
  "The question isn't who is going to let me; it's who is going to stop me. — Ayn Rand",
  "Dream big and dare to fail. — Norman Vaughan",
  "What we achieve inwardly will change outer reality. — Plutarch",
  "It is during our darkest moments that we must focus to see the light. — Aristotle",
  "Nothing is impossible. The word itself says 'I'm possible!' — Audrey Hepburn",
  "Keep your face always toward the sunshine and shadows will fall behind you. — Walt Whitman",
  "Whoever is happy will make others happy too. — Anne Frank",
  "If opportunity doesn't knock, build a door. — Milton Berle",
  "The only person you are destined to become is the person you decide to be. — Ralph Waldo Emerson",
  "Go confidently in the direction of your dreams. Live the life you have imagined. — Henry David Thoreau",
  "When one door of happiness closes, another opens. — Helen Keller",
  "A champion is defined not by their wins but by how they can recover when they fall. — Serena Williams",
  "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. — Jamie Paolinetti",
  "You can never cross the ocean until you have the courage to lose sight of the shore. — Christopher Columbus",
  "What we think, we become. — Buddha",
  "The most wasted of days is one without laughter. — E.E. Cummings",
  "Life shrinks or expands in proportion to one's courage. — Anaïs Nin",
  "If you don't like the road you're walking, start paving another one. — Dolly Parton",
  "I didn't fail the test. I just found 100 ways to do it wrong. — Benjamin Franklin",
  "With the new day comes new strength and new thoughts. — Eleanor Roosevelt",
  "Optimism is the faith that leads to achievement. — Helen Keller",
  "No act of kindness, no matter how small, is ever wasted. — Aesop",
  "Be the change that you wish to see in the world. — Mahatma Gandhi",
  "In order to be irreplaceable one must always be different. — Coco Chanel",
  "Try to be a rainbow in someone's cloud. — Maya Angelou",
  "There is nothing impossible to they who will try. — Alexander the Great",
  "You always pass failure on the way to success. — Mickey Rooney",
  "The best way to predict the future is to create it. — Peter Drucker",
  "Small deeds done are better than great deeds planned. — Peter Marshall",
  "A goal without a plan is just a wish. — Antoine de Saint-Exupéry",
  "Difficult roads often lead to beautiful destinations. — Zig Ziglar",
  "Don't let yesterday take up too much of today. — Will Rogers",
  "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
  "Every moment is a fresh beginning. — T.S. Eliot",
  "The harder you work for something, the greater you'll feel when you achieve it. — Anonymous",
  "Don't stop when you're tired. Stop when you're done. — Wesley Snipes",
  "Wake up with determination. Go to bed with satisfaction. — Dwayne Johnson",
  "Courage is not the absence of fear, but rather the judgment that something else is more important than fear. — Ambrose Redmoon",
  "It's not whether you get knocked down, it's whether you get up. — Vince Lombardi",
  "Your passion is waiting for your courage to catch up. — Isabelle Lafleche",
  "Magic is believing in yourself. If you can do that, you can make anything happen. — Johann Wolfgang von Goethe",
  "If you want something you've never had, you must be willing to do something you've never done. — Thomas Jefferson",
  "The distance between insanity and genius is measured only by success. — Bruce Feirstein",
  "All our dreams can come true if we have the courage to pursue them. — Walt Disney",
  "Success usually comes to those who are too busy to be looking for it. — Henry David Thoreau",
  "Don't be afraid to give up the good to go for the great. — John D. Rockefeller",
  "I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
  "Success is walking from failure to failure with no loss of enthusiasm. — Winston Churchill",
  "Just when the caterpillar thought the world was ending, he turned into a butterfly. — Anonymous",
  "Someone is sitting in the shade today because someone planted a tree a long time ago. — Warren Buffett",
  "Rivers know this: there is no hurry. We shall get there some day. — A.A. Milne",
  "The only way to achieve the impossible is to believe it is possible. — Charles Kingsleigh",
  "What defines us is how well we rise after falling. — Lionel Messi",
  "Never bend your head. Always hold it high. Look the world straight in the eye. — Helen Keller",
];

export default inspirationalQuotes;